### ISSUE TITLE
Stop autoplay next song

### ISSUE THREAD

**Issue by larry77** [moritz-weber/mucke#102]
Hello,
When I select a song I want to listen and the song is over, the next one is played automatically.
Is there any way this behavior can be disabled?
Thanks!

**Comment by moritz-weber** [comment]
Hi, there is currently no such option. Would it be helpful to add this as a fourth looping option? So, in addition to "normal", loop all, loop one, we would get: stop after each song (no matter what the queue looks like).

**Comment by larry77** [comment]
Thanks for the quick reaction.
For me, your proposal would be 100% OK.
