### ISSUE TITLE
Track Numbers Losing First Digit

### ISSUE THREAD

**Issue by MiLLionPiEce** [moritz-weber/mucke#103]
Numbers with three digits and a 0 in the middle have the first digit removed. #0# -> 0# or 101 -> 01

**To Reproduce**
1. Create album with over 100 songs and tagged tracknumbers.
2. Numbers 100-110 will not show up where they should and instead at the start without first digit.

**Expected behavior**
Numbers to show up as shown in the tags.

**Screenshots**
![Number skip](https://github.com/moritz-weber/mucke/assets/132181478/4e06f5b8-ce0e-4eb1-9e13-32fb4aeb526e)

**Smartphone (please complete the following information):**
 - Device: Motorola e6s
 - OS: android 9

**Comment by moritz-weber** [comment]
Thanks for your report. This is curious, I tested this quite extensively, but it looks like there are still some issues.

Could you check what the tags look like exactly? For example, do they contain a disc number? Alternatively, you could also upload one of the problematic files or send the file via email: dev@mucke.rocks

**Comment by moritz-weber** [comment]
There is currently a new implementation of the metadata reader in testing. Could you try out the new build and let me know if this fixes your issue?

https://drive.google.com/file/d/1V1NI5stTFjQdtnyaKv4tX9umyiTCETZc/view?usp=sharing

**Comment by MiLLionPiEce** [comment]
This fixed the issue. Thanks.
