### ISSUE TITLE
Play/Pause Button stuck in invalid state after playback is interrupted by calls

### ISSUE THREAD

**Issue by FriederHannenheim** [moritz-weber/mucke#104]
**Describe the bug**
If you get a call while playing music with Mucke the Play/Pause button in the media player notification will be stuck in an invalid state and will not work anymore.

**To Reproduce**
1. Start playing a song with mucke
2. Call someone (They don't need to answer you can hang up immediately)
3. Pull down notifications and try to pause/resume playback

**Expected behavior**
The button can pause and resume playback as normal

**Screenshots**
(Audio is playing but was removed because of copyright)
https://github.com/moritz-weber/mucke/assets/41985738/1b464b22-c34c-466f-85ee-a9d288ac1dc0

**Smartphone (please complete the following information):**
 - Device: OnePlus 8T
 - OS: Android 12
 - Version 1.3.1

**Comment by moritz-weber** [comment]
This is a known issue: #68
