### ISSUE TITLE
[nightly] scan doesn't work

### ISSUE THREAD

**Issue by ildar** [moritz-weber/mucke#106]
**Describe the bug**
`Update database` doesn't work, 0 tracks remain

**To Reproduce**
1. install the CI build from https://github.com/moritz-weber/mucke/actions
2. add Music folder in Settings
3. tap `Update database`
4. the app scans but doesn't add tracks to its db

**Smartphone (please complete the following information):**
 - Device: AGM H3
 - OS: Android 13

**Additional context**
Logs show that tracks are scanned. But `app_flutter/db.sqlite` isn't touched, mtime is 3 hours ago.

**Comment by moritz-weber** [comment]
Yeah, I realized this issue too. Although for me, it only fails for a couple of songs.

See #99 for this topic.
