### ISSUE TITLE
Cover images no longer being imported

### ISSUE THREAD

**Issue by jdg2011** [moritz-weber/mucke#125]
**Describe the bug**
After updating to version 5.17.1 (I believe I was on 5.16.6 before), when updating library with new music, cover art is no longer being added. 

**To Reproduce**
1. Add new music files to device with a file named "cover.jpg"
2. Open mucke, go to Settings and tap "Update Library."
3. Wait for update to complete.
4. Look up new music in library.

**Expected behavior**
I expected the album art to be visible, like it always has since I started using mucke a couple months ago.

**Screenshots**
[Missing album art](https://imgur.com/yT1QJ4I)
[Music files with cover art file](https://imgur.com/fuJZgHE)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: GrapheneOS
 - Version 13

**Additional context**
I have tried to delete and re-add music multiple times but no effect. I also installed Simple Music Player and imported the same music, and it does display the album art.

**Comment by moritz-weber** [comment]
This is a known issue (see #60). A potential fix is available in a development build in the last comment of that issue. It would really help me, if you could try that build and let me know if it works for you.

Out of curiosity: Where did you get that version number from? The current release should be 1.4

**Comment by jdg2011** [comment]
Ah, I must apologize on two fronts. I thought I'd made sure the problem hadn't been brought up before, but evidently I overlooked that one. And I was looking at the wrong app in F-droid when I wrote the version number. I am using 1.4. I will try that development build and get back to you.
