### ISSUE TITLE
my program is in russian

### ISSUE THREAD

**Issue by cyberhardt** [moritz-weber/mucke#127]
**Describe the bug**
for some reason most of the text on the screen is in russian, with the exception of the "Miscellaneous" section of the settings and the "Your Playlists" phrase. everything else is in russian.

**To Reproduce**
1. Download latest version as of 2nd august 2023
2. Run the program
3. See text in russian

**Expected behavior**
for it to be in english or for me to be able to change it

**Screenshots**
![image](https://github.com/moritz-weber/mucke/assets/107224222/13435434-770d-4783-8a08-324f169daf98)
![image](https://github.com/moritz-weber/mucke/assets/107224222/373cadf9-4451-4df7-9fd4-38775151751a)

**Smartphone (please complete the following information):**
 - Device: Samsung S10
 - OS: Android 
 - Version: 12

**Additional context**
I've installed it a couple days ago. I remember it being in english then, but now it is in russian.

**Comment by moritz-weber** [comment]
Which languages do you have installed on your phone and how are they ordered?

**Comment by cyberhardt** [comment]
> Which languages do you have installed on your phone and how are they ordered?

I have english, russian and japanese, but russian is on 2nd place and not first

**Comment by cyberhardt** [comment]
oh ok, I fixed it by removing english and putting it again in first
