### ISSUE TITLE
When only a single song is in the Queue, manually queued songs won't play after

### ISSUE THREAD

**Issue by FriederHannenheim** [moritz-weber/mucke#128]
**Describe the bug**
When you play a single song and manually put songs into the queue after that song, playback will stop after the first song and the manually queued songs won't play.

**To Reproduce**
1. Search for a song and put it into the queue (it needs to be alone in the queue so don't play a song from an album)
2. Search for another song and add it to manually queued songs
3. Wait for the first song to finish
4. Playback will halt and the manually queued song will not play

**Expected behavior**
The manually queued song should play

**Smartphone (please complete the following information):**
 - Device: Oneplus 8T
 - OS: Android 12
 - Version v1.4.0

**Comment by moritz-weber** [comment]
The changes in the branch fix the issue. I am almost certain that there are still issues in edge cases, but the problematic function is only called in a very limited way right now, so we should be good.

Nonetheless, I will test this a couple of days before merging. We really need automated tests for this kind of stuff 😅
