### ISSUE TITLE
Add french translation

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [moritz-weber/mucke#133]
Hello again, sorry for opening so many issues '^^
I'm not too sure how often you check weblate (or if you have automatic integration), so i wanted to say that the French translation is 100% done, so it would be pretty nice if it could be added!

Edit: woops, didn't mean to mark this as a feature, but i can't remove it...

**Comment by moritz-weber** [comment]
No worries, thanks for your contribution.

Weblate should update the pull request tomorrow. After merging the changes, I can activate the translation.
