### ISSUE TITLE
app crash on HyperOS

### ISSUE THREAD

**Issue by mmeyran** [moritz-weber/mucke#176]
**Describe the bug**
When starting playback, the app crashes systematically after half a second. File format has no impact (mp3, vorbis, opus). Clearing up the app's cache and all files (clean install) has no effect.

**To Reproduce**
1. install and setup mucke with all authorizations
2. start blayback
3. app crashes.

**Expected behavior**
music playback that won't crash...

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi 11
 - OS: HyperOS  / Android 13
 - Version 1.0.1.0 TGKEUXM /  TKQ1.221114.001

**Additional context**
Used to work well on that same phone with MIUI 14 on that same phone. Not sure what version of Android it was running though, I think it was 13 already.

**Comment by stop0xA** [comment]
I'm using MIUI 14 on android version 13 and working fine, if that helps. 

On a POCO F4

**Comment by mmeyran** [comment]
It's a HyperOS bug, other sound apps are showing similar symptoms. Solved in later releases of the OS, you can close this bug report.

**Comment by mmeyran** [comment]
as such, closing the bug.
