### ISSUE TITLE
can not install on android 12

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [moritz-weber/mucke#28]
### My smartphone: Samsung S21 5G, Android 12
I tried to install the [1.0.1](https://github.com/moritz-weber/mucke/releases/tag/v1.0.1) apk, but I get the following message

![photo1665251234](https://user-images.githubusercontent.com/61406324/194720758-0a54dd1a-2a65-4fa8-990b-d85fbe53a195.jpeg)

**Comment by moritz-weber** [comment]
Thanks for letting me know. I couldn't build the project for Android 12 either.
The problem should now be fixed. You can try this build: https://github.com/moritz-weber/mucke/suites/8681240740/artifacts/391257053

If it works, I'll bump the version number to have a new release.

**Comment by mondlicht-und-sterne** [comment]
![photo1665259627](https://user-images.githubusercontent.com/61406324/194726168-7e00c5d3-e1d1-45ce-aa79-f911fb63a70d.jpeg)
![photo1665259677](https://user-images.githubusercontent.com/61406324/194726198-f9d06807-e9d4-492e-85b1-82635ebcb319.jpeg)
![photo1665259731](https://user-images.githubusercontent.com/61406324/194726219-868e26ef-475f-46d6-983c-cb846afbe0ab.jpeg)
