### ISSUE TITLE
Support more file types

### ISSUE THREAD

**Issue by BrightDV** [moritz-weber/mucke#29]
Hello,
First of all, thanks for this great app.
I have mainly .m4a songs on my phone, so it would be great to have the possibility to play these songs. 
If it is not possible, maybe a mention of which type of files are supported can be useful.

**Comment by moritz-weber** [comment]
Hi, thanks for the feedback.
This is definitely one of my top priorities right now. I also want to add support for flac and ogg files.
The current limitation is the tag reader that extracts the metadata from the files - which only works for ID3...
However, this (https://pub.dev/packages/on_audio_query) looks promising. I'll see what I can do with it.

For now, I'll add the info to the readme.

**Comment by moritz-weber** [comment]
@BrightDV there is a new version I'm currently testing: https://github.com/moritz-weber/mucke/actions/runs/3315859322
This should support the most common file types (except WMA). 

I'd be happy if you could give me feedback on how well this works for you.

**Comment by BrightDV** [comment]
I only have .m4a files on my device but it works very well for those, thanks!
However, I found an other issue, where do the artists of an album come from? They are not the same as the song even if there is only one song in the album.
![Screenshot_20221025-080428](https://user-images.githubusercontent.com/92821484/197695088-5fee600b-7612-4d38-9e40-0f22d91da8d3.png)

**Comment by moritz-weber** [comment]
I check if the song has an `album_artist` tag and then use this for the album. Maybe you can check the tags of your file with a tag reader/editor to confirm that the `album_artist` tag is read correctly.

For mp3, the metadata seems to be fine, but I found some issues with flac files in my library.

**Comment by BrightDV** [comment]
You're right, the tags are read correctly... Sorry.
