### ISSUE TITLE
Add like button in media notification

### ISSUE THREAD

**Issue by FriederHannenheim** [moritz-weber/mucke#34]
Spotify has a like button directly in the media notification, it would be cool if this app had it too.
![grafik](https://user-images.githubusercontent.com/41985738/208446947-6c9e11d1-ca3d-4f8b-9c89-de4fd97761aa.png)

**Comment by moritz-weber** [comment]
Thanks for the suggestion. I really like the idea.
I have to look into the capabilities of the plugin I use for the notification handling. Can't promise anything right now.
