### ISSUE TITLE
Setting for when a song is marked as listened

### ISSUE THREAD

**Issue by FriederHannenheim** [moritz-weber/mucke#38]
I've noticed that songs arw only marked as listened after listening to it for some time and not if you just listen to 5 seconds of it. A setting to set the time one needs to listen to a song for it to increment the listen counter would be great.

**Comment by moritz-weber** [comment]
Yes, it's currently set to count one play after 95% of the song duration. I'd probably go with a percentage value again, as I think it is more flexible than an absolute value, but I can surely add an option for this to the settings.
