### ISSUE TITLE
Updating library infinite loading

### ISSUE THREAD

**Issue by Der-Flip** [moritz-weber/mucke#50]
I experience an infinite loading when trying to update my library.

here's my testing to when it happens:

✅updates successful
❌infinite loading

✅[device storage]\Music\\[any folder]
✅[SD storage]\Music\\[any folder]
❌[SD storage]\Music

I am unable to test, whether the music folder moved from SD Card to internal storage would load, as it is too large (7.243 entries, 49,08 GB total).
the subfolder that loaded successfully on SD and internal both have a size of roughly 1500files at 4.5gb and it loads within 10 to 15 seconds. the main music folder though won't be loaded even after hours.

device info:
redmi 9c
android 10 (QP1A.190711.020
miui 12 (12.0.14 stable (QCREUXM))

**Comment by moritz-weber** [comment]
Thank you for this bug report. I don't think that the file number or size is a problem.
My best guess would be that the app has trouble reading some of the files.

You could test this by adding one subfolder after the other from your SD/Music folder to the library and check when the update fails. To assess your issue properly, I'll first have to set up comprehensive logging for this process and enable sharing the logs. This has a high priority for me, but it can still take a while until it is implemented and shipped.

**Comment by cd-FileX** [comment]
In 2 hours of testing I could find out that it seems to be metadata of mp3 files. Maybe a not recognized tag or something. The files that are not able to be imported are, for example, also not openable with Metro Music Player but with Audify or Avee Player. 
I have uploaded these songs to https://github.com/cd-FileX/broken-songs-mucke for testing purposes with your app (only).

**Comment by moritz-weber** [comment]
Thanks for your investigation. I tried the first of these songs with the newly released v1.4 and didn't have any issues. I also think that the new implementation of the file scanner should not crash when a file can't be read. It should just continue with the next file.

**Comment by cd-FileX** [comment]
Yup, works with 1.4 for me as well

**Comment by Der-Flip** [comment]
I finally got around to testing. After 4 hours and tediously moving files around I can now say my issue was caused by a .DS_Store file...

Found another issue though: files are being ignored...
