### ISSUE TITLE
Sorting Naturally

### ISSUE THREAD

**Issue by Ynray** [moritz-weber/mucke#59]
As far as I can tell, sorting is currently done alphabetically, which leads to unexpected behaviour when playing audio files in correct album order that contain numbers. Currently files will be played in this order:

- Song 1
- Song 10
- Song 100
- Song 2
- Song 3

Expected behaviour:

- Song 1
- Song 2
- Song 3
- Song 10
- Song 100

Solution could probably be sorting by natural compare rather than alphabetical

**Comment by moritz-weber** [comment]
Thanks for your report. Could you specify in which situation/view you find this behavior? When playing an album, the songs should be sorted by the song number, not alphabetically.

**Comment by Ynray** [comment]
I am referencing especially to audio plays that have album with titles "Chapter 1" until "Chapter 100" (yes, this is the title of the ID3v2 tag), in my current example the track number does exists correctly as v2 tag, the v1 tag seems to be empty.
This behaviour applys to classical artists too where sonata tracks are split up to several mp3 files that are just titled "Part 1" - "Part 100" with no track number available.
