### ISSUE TITLE
Adding info to songs

### ISSUE THREAD

**Issue by CoolerWuffi** [moritz-weber/mucke#61]
**Is your feature request related to a problem? Please describe.**
When i download some music from newpipe i get a m4a file this file has no coverart or artist name on it.

**Describe the solution you'd like**
Add a button so you can edit the coverart and name in the player .
For the coverart direct the user to his filesystem so he can pic a cover.

For the name make a box were the user can type in a name

**Describe alternatives you've considered**
Add a button so you can edit the coverart and name in the player.
Direct the user to a cover page from ex. Youtube music or spotify (linke in playnite if you pick a cover for a game over there) and if the user cant find a cover over there direct the user to his filesystem so he can pic a cover over there.

For the name make a box were the user can type in a name

**Comment by moritz-weber** [comment]
Thanks for the suggestion. I can see how such a feature would be useful.
However, editing music files adds a lot of complexity to the app. Therefore, I won't consider such a functionality right now.

For now, I'll close the issue. If someone else really wants to implement this, we can integrate it.
