### ISSUE TITLE
Copycat/clone of mucke on Google Play

### ISSUE THREAD

**Issue by Poussinou** [moritz-weber/mucke#63]
Hi @moritz-weber 

I just found this copy of Mucke on Google Play https://play.google.com/store/apps/details?id=rocks.muvgh from [this developer](https://play.google.com/store/apps/developer?id=Schnupfeld).

It's full of ads, and it's clearly a violation of the GNU GPL v3 license. It's developer's page is full of copycats of other FLOSS apps...

You can follow the procedure [here](https://github.com/TeamNewPipe/NewPipe/issues/539#issuecomment-1399222536) if you want to send a takedown request to Google Play.

**Comment by moritz-weber** [comment]
Thanks for the heads up. I really didn't expect anything like that for this small hobby project...

**Comment by Poussinou** [comment]
I've seen copycats of apps with like two stars on GitHub and 100 downloads of the official app... You never know what they will do.

Still a good thing to make your app open source, and GNU GPL v3 is the best license to counter this.

Don't hesitate to report the app to Google Play, and report it here if you find other copycats :)

**Comment by Poussinou** [comment]
This copycat has been taken down. I'm closing this Issue.

Please report it here if you find other copycats in the future.
