### ISSUE TITLE
opus codec support

### ISSUE THREAD

**Issue by kityr** [moritz-weber/mucke#65]
**Is your feature request related to a problem? Please describe.**
The player seems very cool, but all my music are opuses converted from flacs, and they don't get detected even if I add opus to the extension list in the settings.

**Describe the solution you'd like**
I'd like for opus codec to be supported.

**Additional context**
It should be relatively simple to do, since the codec is open source iirc. It also seems to be the best choice considering the quality to size ratio: https://wiki.hydrogenaud.io/index.php?title=Opus

**Comment by logcatdog** [comment]
Also would love opus support. Thanks.

**Comment by moritz-weber** [comment]
Yeah, I would love that too... Currently, I'm relying on a third-party plugin for audio playback (https://github.com/ryanheise/just_audio). It's a great plugin, but it is limited to the codecs supported by Android directly.

Getting this to work would require a significant rewrite of large parts of the code. I don't think that I can implement this on my own.

If you want to show a need for this, you can upvote this issue: https://github.com/ryanheise/just_audio/issues/607 (please don't spam)

**Comment by moritz-weber** [comment]
@kityr I just tested this with some files I converted from flac to opus. Didn't have a problem (except with some metadata, which is a known issue). Would you mind sending me one of the files that don't work for you?

**Comment by kityr** [comment]
> @kityr I just tested this with some files I converted from flac to opus. Didn't have a problem (except with some metadata, which is a known issue). Would you mind sending me one of the files that don't work for you?

I have just tried again, and everything seems to work, actually. I even might have just not noticed the "update library" button. I feel so stupid right now, sorry for taking your time
