### ISSUE TITLE
FLAC Dates show up as 'null'

### ISSUE THREAD

**Issue by krllschmdt** [moritz-weber/mucke#70]
First of all I'd like to thank you so much for making such an amazing music player app! Absolutely love it

**To Reproduce**

```bash
metaflac --show-tag=date 'Molchat Doma - etazhi (2018) - 01 na dne.flac'        
DATE=2018
```

1. See `DATE` is set
2. Go to album overview of the FLAC album

**Expected behavior**
See the set date instead of null

![Screenshot_20230413-174110_mucke](https://user-images.githubusercontent.com/79871631/231818794-dce6b7fe-409b-4f71-ae8a-205ab8c4cc51.png)

**Smartphone (please complete the following information):**
 - Device: Fairphone 3+
 - OS: /e/OS
 - Version 1.9.1

**Comment by FriederHannenheim** [comment]
This seema to be the case for id3v2.4 tags too
