### ISSUE TITLE
Play/Pause multimedia button doesn't work

### ISSUE THREAD

**Issue by ildar** [moritz-weber/mucke#75]
**Describe the bug**
pushing Play/Pause on the BT headphone doesn't do anything.
Other apps work fine.

**Smartphone (please complete the following information):**
 - Device: AGM H3
 - OS: Android 13 / LineAgeOS 20.1
 - Version: 1.2.0

**Comment by moritz-weber** [comment]
That's weird, I didn't have any issues with this so far. The app should log the button presses though.

Can you provide me with one of the log files under 'Android/data/rocks.mucke/files/logs'?

There should be one file per day, so pick one where you used your BT device.

**Comment by ildar** [comment]
I am sorry I missed your reply.
I've dug a little and got you something: app log and adb log.
Thanks!

**Comment by ildar** [comment]
I am sorry I missed your reply.
I've dug a little and got you something: [app log 20230518_060000.txt](https://github.com/moritz-weber/mucke/files/11510692/20230518_060000.txt) and [adb.logcat.txt](https://github.com/moritz-weber/mucke/files/11510696/adb.logcat.txt)
Thanks!

**Comment by marcofeltmann** [comment]
No issues on Xioami Pocophone F1 with LineageOS 20.0 and Sennheiser HD 4.50 BTNC as long as Mucke is running.

BTW, the AGM looks totally nice. :heart:

**Comment by ildar** [comment]
you mean that Pause media button is caught? that's weird. Can you make a
debug build logging all the media buttons around?
BTW, AFAIK Auxio is also a Flutter app. And the Pause works there.

**Comment by moritz-weber** [comment]
@ildar no problem, thanks for the log files.

The log file suggests that 
1) the button presses are recognized: `I PlatformIntegrationDataSourceImpl: MediaButton.media`
2) the "play" method should have been called twice: `D PlatformIntegrationDataSourceImpl: play`
3) for some reason, the "pause" method is not called

The debug build is too large to add to a comment, so here is a Google Drive link: https://drive.google.com/file/d/1BJPcEeEq3yByM29TrIsIvPiwdk_A3zC2/view?usp=sharing

It would also be helpful, if you could describe the actions that you performed and the reactions of the app. (If anything happens at all.)

**Comment by ildar** [comment]
Thanks for the debug build.

> Message ID: ***@***.***>
>
Regarding my actions: i press the button (just one button) many times.
Playback starts but never stops

**Comment by moritz-weber** [comment]
Thanks, so your actions match the logged events. That's a good start :sweat_smile: 
Let me know, when you have the new logs from the debug build.

**Comment by ildar** [comment]
got the new interesting log with your debug build.

**Comment by ildar** [comment]
works great! now I'm waiting for the next release )))
Thanks a lot!!!
