### ISSUE TITLE
App suddenly turned into German after 1.3 update

### ISSUE THREAD

**Issue by gianmarcogg03** [moritz-weber/mucke#79]
**Describe the bug**
When I updated to version 1.3.0, the language of the app turned from English to German and I cannot change it.

**To Reproduce**
1. Update to version 1.3.0

**Expected behavior**
The language should have still been in English.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6a
 - OS: GrapheneOS
 - Version 13

**Additional context**
My system language is Italian.

**Comment by Tonus1** [comment]
Same here.
No settings to change that as far as I know.

**Comment by moritz-weber** [comment]
It would be nice, if all mucke users learned German this way, but obviously this wasn't intended ;)

I didn't know that the translation priority in Flutter was alphabetical, so _de_ before _en_.  Should be fixed in the next release.
