### ISSUE TITLE
Player widget

### ISSUE THREAD

**Issue by MagicManWithLinux** [moritz-weber/mucke#86]
I think it would be great to make a similar widget.
![Screenshot_20230515-102029_Nova7_1.png](https://github.com/moritz-weber/mucke/assets/94105164/d440f569-3a9e-4d89-9122-6e8ec64b50c3)

**Comment by ildar** [comment]
dup of https://github.com/moritz-weber/mucke/issues/56 ?

**Comment by MagicManWithLinux** [comment]
> dup of #56 ?

Hm strange. Search didn't show me this.
