### ISSUE TITLE
Please turn the Weblate bot frequency down

### ISSUE THREAD

**Issue by FriederHannenheim** [moritz-weber/mucke#97]
I watch this repository because I'm interested in mucke and want to see it being developed. Currently I get spaed by weblate bot emails because it creates a new PR every 5 minutes or so. Please turn it down to once a day. It's not needed every 5 minutes

**Comment by moritz-weber** [comment]
I triggered the commits/pull requests manually yesterday because I was fixing the settings. Previously, the forked repository and my repository were diverging. Now everything should be fine.
